// Mock data for static site generation
export const mockSeafarers = [
  {
    id: "59844513",
    displayId: "SEA-59844513",
    personal: {
      firstName: "Pesho",
      lastName: "Kostov",
      nationality: "ALGERIAN",
      birthDate: "1999-04-13",
      rank: "First Officer",
      presentEmployer: "",
      vesselType: "Crude Oil",
      homeAirport: "",
      availabilityDate: "2025-04-30",
      contractDuration: "",
      email: "",
      phone: "0878225671",
      address: "Ул. Васил Левски 68",
      salary: "",
      nextVessel: "test next vessel123",
      assignmentDate: "2025-05-01",
      personalId: ""
    },
    status: "Unavailable",
    lastVessel: "MSC MARIELLA",
    certificates: [],
    voyages: [],
    performance: [],
    experience: { rank: 0, total: 0 },
    travelHistory: [],
    expenses: [],
    vesselType: "Crude Oil",
    remark: ""
  },
  {
    id: "79dec2a3-2eb1-4943-9f97-1ccfc4a626f5",
    displayId: "SEA-00001",
    personal: {
      firstName: "John",
      lastName: "Smith",
      nationality: "AMERICAN",
      birthDate: "1980-05-15",
      rank: "Captain",
      presentEmployer: "",
      vesselType: "Container",
      homeAirport: "",
      availabilityDate: "2023-12-01",
      contractDuration: "",
      email: "john.smith@example.com",
      phone: "+1234567890",
      address: "123 Main St, New York, USA",
      salary: "",
      photoUrl: null,
    },
    status: "ONSHORE",
    lastVessel: "MAERSK ALABAMA",
    certificates: [],
    voyages: [],
    performance: [],
    experience: { rank: 5, total: 15 },
    travelHistory: [],
    expenses: [],
    vesselType: "Container",
    remark: ""
  },
  {
    id: "79fe0794-1b0e-4f8d-a5f2-11986d53d521",
    displayId: "SEA-00002",
    personal: {
      firstName: "Maria",
      lastName: "Lopez",
      nationality: "SPANISH",
      birthDate: "1985-08-23",
      rank: "Chief Engineer",
      presentEmployer: "",
      vesselType: "Bulk Carrier",
      homeAirport: "",
      availabilityDate: "2024-02-15",
      contractDuration: "",
      email: "maria.lopez@example.com",
      phone: "+3456789012",
      address: "45 Calle Mayor, Madrid, Spain",
      salary: "",
      photoUrl: null,
    },
    status: "ONBOARD",
    lastVessel: "MADRID MAERSK",
    certificates: [],
    voyages: [],
    performance: [],
    experience: { rank: 7, total: 12 },
    travelHistory: [],
    expenses: [],
    vesselType: "Bulk Carrier",
    remark: ""
  },
  {
    id: "c4e0e3b2-7826-4a2f-bc5e-f9bb16945d23",
    displayId: "SEA-00003",
    personal: {
      firstName: "Dimitri",
      lastName: "Petrov",
      nationality: "RUSSIAN",
      rank: "Chief Officer",
      photoUrl: "",
    },
    status: "ASSIGNED"
  },
  {
    id: "b3d2c1a0-5678-4e3d-9876-a1b2c3d4e5f6",
    displayId: "SEA-00004",
    personal: {
      firstName: "James",
      lastName: "Wilson",
      nationality: "BRITISH",
      rank: "Second Engineer",
      photoUrl: "",
    },
    status: "ONSHORE"
  },
  {
    id: "e5d4c3b2-8765-4f3e-a9b8-c7d6e5f4a3b2",
    displayId: "SEA-00005",
    personal: {
      firstName: "Hiroshi",
      lastName: "Tanaka",
      nationality: "JAPANESE",
      rank: "Bosun",
      photoUrl: "",
    },
    status: "ONBOARD"
  }
]; 